<?php
/**
 * Plugin Name: Divider Block
 * Plugin URI:  https://github.com/your-username/divider-block
 * Description: A simple, accessible, and configurable Divider / Separator Gutenberg block (no build tools required).
 * Version:     1.0.0
 * Author:      Generated by ChatGPT (you)
 * License:     GPLv2 or later
 * Text Domain: divider-block
 *
 * @package divider-block
 */

if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

function divider_block_register_block() {
    $dir = plugin_dir_path( __FILE__ );
    $url = plugin_dir_url( __FILE__ );

    // Register editor script (no build step; uses WP provided globals)
    wp_register_script(
        'divider-block-editor',
        $url . 'src/editor.js',
        array( 'wp-blocks', 'wp-element', 'wp-editor', 'wp-components', 'wp-i18n' ),
        filemtime( $dir . 'src/editor.js' )
    );

    // Register editor styles
    wp_register_style(
        'divider-block-editor-style',
        $url . 'src/editor.css',
        array( 'wp-edit-blocks' ),
        filemtime( $dir . 'src/editor.css' )
    );

    // Register front-end styles
    wp_register_style(
        'divider-block-style',
        $url . 'src/style.css',
        array(),
        filemtime( $dir . 'src/style.css' )
    );

    register_block_type( 'custom/divider', array(
        'editor_script' => 'divider-block-editor',
        'editor_style'  => 'divider-block-editor-style',
        'style'         => 'divider-block-style',
    ) );
}
add_action( 'init', 'divider_block_register_block' );
